### ISSUE TITLE
Make ethereum-remote-client declare its own version

### ISSUE THREAD

**Issue by bbondy** [brave/brave-core-crx-packager#181]
We should do this so we can easily bisect things later. Also so that the dev server and prod server use the same version.

**Comment by mihaiplesa** [comment]
Do we still use ethereum-remote-client?

**Comment by bbondy** [comment]
Only if a user turns it on via about://flags brave://flags/#ethereum_remote-client_new-installs 
We do plan to remove that option though.

**Comment by bbondy** [comment]
We can close this.
