### ISSUE TITLE
Automatically determine the HTTPSE version to use from latest XPI 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-core-crx-packager#22]
Cross posting from https-everywhere-builder because I think we're likely to miss it there if we don't track it here.

https-everywhere-builder has `xpiVersion` in it at path `scripts/preloadHTTPSE.js`.
We should extract the XPI (zip) and take the manifest.json's version instead. 

https://github.com/brave/https-everywhere-builder/issues/7

**Comment by fmarier** [comment]
The original issue was resolved in https://github.com/brave/https-everywhere-builder/pull/12 and is the recommended approach suggested by EFF.
