### ISSUE TITLE
Update scripts to eliminate vault updater

### ISSUE THREAD

**Issue by emerick** [brave/brave-core-crx-packager#30]
Now that we're using the go-update server and DynamoDB, there's no need to update vault-updater so we can remove the `--vault-updater-path` command-line option from our packaging scripts. In fact, we can probably just drop the release-tools dependency completely and migrate the smarts to upload to S3 into the packager.

cc: @mihaiplesa

**Comment by mihaiplesa** [comment]
Removed obsolete version from all Jenkins jobs.
