### ISSUE TITLE
Production repo should not have a dependency in brave-experiments

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-core-crx-packager#470]
This is depending on brave-experiments/Speedreader which is not covered by any of our security policies: https://github.com/brave/brave-core-crx-packager/blob/master/package.json#L19

We have a policy that any prod repos should only depend on repos in brave or brave-intl.

**Comment by antonok-edm** [comment]
see also: https://github.com/brave/brave-core-crx-packager/issues/471

**Comment by diracdeltas** [comment]
closing in favor of #471
