### ISSUE TITLE
Publisher Proof key is required for building adblock component 

### ISSUE THREAD

**Issue by akki91** [brave/brave-core-crx-packager#637]
While running the script `package-ad-block` it throws the error if the publisher proof key is not passed in command line arguments. As per the readme, this key is not required and only the private key `.pem` needs to be passed into the arguments.

**Comment by antonok-edm** [comment]
@akki91 if you use the `--local-run` flag, it shouldn't throw any errors about the publisher proof key - does that work for you?

**Comment by akki91** [comment]
@antonok-edm Yes that is correct and I was able to run all components properly, thanks 
However for actual upload and building components for our own production use case, a `publisher-proof-key` is required, can it be same as the private key used for creating the `.crx` file?

**Comment by akki91** [comment]
Was able to generate and use it, closing this issue. 
Thanks
