### ISSUE TITLE
Standardize command to pass key-file for all crx command

### ISSUE THREAD

**Issue by linhkikuchi** [brave/brave-core-crx-packager#863]
This PR https://github.com/brave/devops/pull/11212 to shrink the code base and standardize the method to build crx package. However, some of the package use `--key` and some uses `--key-file` to pass in the key. We need to standardize this across all packages.

**Comment by linhkikuchi** [comment]
@antonok-edm I did a quick search and see we have half using `--key` and half using `--key-file`. What would you recommend to standardize here? FYI on devops repo, we are currently use `--key` to pass in key file. However, we can update either way.

**Comment by antonok-edm** [comment]
@linhkikuchi great idea, I didn't realize that.

Let's do `--key-file`, since that's what I have in https://github.com/brave/brave-core-crx-packager/pull/844/files#diff-e658c4d9d47f8fcbd582d7d65a9c38f510459f827d58dd7ea2c5c03aa4bd12c0R14
