### ISSUE TITLE
Remove unsupported preprocessor-based filters from an adblock list

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-core-crx-packager#923]
We don't currently support [preprocessor directives](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition) in adblock-rust. This leads to issues when upstream lists push filters that are only meant for Firefox. We should filter out rules that are FF-only on the backend.

chrmod shared https://gist.github.com/chrmod/f26267a9fcd3f39d9adfd401f5c5b168 on our shared Slack which we can adapt pretty easily to filter out rules. We'd want to remove both `cap_html_filtering` and `env_firefox`.

**Comment by antonok-edm** [comment]
I recommend adding the filtering [here](https://github.com/brave/brave-core-crx-packager/blob/master/scripts/generateAdBlockRustDataFiles.js#L69), where we're already doing another preprocessing step.
